<a href="https://colab.research.google.com/github/hansjang/Py_Radar/blob/main/%EB%8D%B0%EC%8B%B8%EB%9D%BC%EB%A9%B4Part4_P99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/hansjang/Py_Radar.git

import shutil
shutil.move('Py_Radar/data', '/content/data')

Cloning into 'Py_Radar'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 123 (delta 58), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (123/123), 5.26 MiB | 6.72 MiB/s, done.
Resolving deltas: 100% (58/58), done.

'/content/data'

In [ ]:
# 폴더와 그 안의 모든 파일을 삭제
# !rm -rf /content/Py_Radar
# !rm -rf /content/data

In [72]:
# 데이터 불러오기
import numpy as np
import pandas as pd

df = pd.read_csv('/content/data/Greats47.csv', encoding='utf-8')

display(df.head())
display(df.shape)   # (47,11)

,NAME,AGE,BIRTH,DEATH,JOB,MBC,KBS,SBS,TVN,JTBC,TOTAL
0,홍대용,조선후기,1731-03-01,1783-10-23,실학자,0,1630000,0,1170000,820000,3620000
1,정약종,조선후기,1760-03-10,1801-02-26,종교인,0,599000,0,61000,0,660000
2,박제가,조선후기,1750-11-05,1805-07-06,실학자,4130000,14613000,0,4102000,1826000,24671000
3,홍경래,조선후기,1780-01-01,1812-05-29,운동가,2880000,4134000,0,682000,1026000,8722000
4,신윤복,조선후기,1758-01-01,1814-12-31,화가,1778000,8691000,0,2284000,202000,12955000

(47, 11)

# 범주형변수 처리 => 라벨인코딩, 원핫인코딩

In [58]:
# 순서형 변수의 라벨 인코딩(Label Encoding)
from sklearn.preprocessing import LabelEncoder

# Label Encoder 적용
encoder = LabelEncoder()
df['AGE_encoded'] = encoder.fit_transform(df['AGE'].values.ravel()) # 1차원 배열로 전달

display(df[['AGE', 'AGE_encoded']])  # 조선후기 = 2, 일제강점기 = 1, 대한민국 = 0

      AGE  AGE_encoded
0    조선후기            2
1    조선후기            2
2    조선후기            2
3    조선후기            2
4    조선후기            2
5    조선후기            2
6    조선후기            2
7    조선후기            2
8    조선후기            2
9    조선후기            2
10   조선후기            2
11   조선후기            2
12  일제강점기            1
13  일제강점기            1
14  일제강점기            1
15  일제강점기            1
16  일제강점기            1
17  일제강점기            1
18  일제강점기            1
19  일제강점기            1
20  일제강점기            1
21  일제강점기            1
22  일제강점기            1
23  일제강점기            1
24  일제강점기            1
25  일제강점기            1
26  일제강점기            1
27  일제강점기            1
28  일제강점기            1
29  일제강점기            1
30  일제강점기            1
31   대한민국            0
32   대한민국            0
33   대한민국            0
34   대한민국            0
35   대한민국            0
36   대한민국            0
37   대한민국            0
38   대한민국            0
39   대한민국            0
40   대한민국            0
41   대한민국            0
42   대한민국            0
43   대한민국            0
44   대한민국            0
45   대한민국            0
46   대한민국            0

In [55]:
# 순서를 유지한 인코딩(Ordinal Encoding)
from sklearn.preprocessing import OrdinalEncoder

# Ordinal Encoder 적용
encoder = OrdinalEncoder(categories=[['조선후기', '일제강점기', '대한민국']])
df['AGE_encoded'] = encoder.fit_transform(df[['AGE']])
df['AGE_encoded'] = df['AGE_encoded'].astype(int)   # float로 반환되기 때문에 int로 변환

display(df[['AGE','AGE_encoded']]) # 조선후기 = 0, 일제강점기 = 1, 대한민국 = 2

      AGE  AGE_encoded
0    조선후기            0
1    조선후기            0
2    조선후기            0
3    조선후기            0
4    조선후기            0
5    조선후기            0
6    조선후기            0
7    조선후기            0
8    조선후기            0
9    조선후기            0
10   조선후기            0
11   조선후기            0
12  일제강점기            1
13  일제강점기            1
14  일제강점기            1
15  일제강점기            1
16  일제강점기            1
17  일제강점기            1
18  일제강점기            1
19  일제강점기            1
20  일제강점기            1
21  일제강점기            1
22  일제강점기            1
23  일제강점기            1
24  일제강점기            1
25  일제강점기            1
26  일제강점기            1
27  일제강점기            1
28  일제강점기            1
29  일제강점기            1
30  일제강점기            1
31   대한민국            2
32   대한민국            2
33   대한민국            2
34   대한민국            2
35   대한민국            2
36   대한민국            2
37   대한민국            2
38   대한민국            2
39   대한민국            2
40   대한민국            2
41   대한민국            2
42   대한민국            2
43   대한민국            2
44   대한민국            2
45   대한민국            2
46   대한민국            2

In [60]:
# 범주형 변수의 더미변수화 (pd.get_dummies)
import pandas as pd

df_encoded = pd.get_dummies(df, columns=['AGE'])

display(df_encoded.head())  # 새로운 변수 AGE_대한민국, AGE_일제강점기, AGE_조선후기가 생성됨
                            # 변수값은 True, False로 반환됨

,NAME,BIRTH,DEATH,JOB,MBC,KBS,SBS,TVN,JTBC,TOTAL,AGE_대한민국,AGE_일제강점기,AGE_조선후기
0,홍대용,1731-03-01,1783-10-23,실학자,0,1630000,0,1170000,820000,3620000,False,False,True
1,정약종,1760-03-10,1801-02-26,종교인,0,599000,0,61000,0,660000,False,False,True
2,박제가,1750-11-05,1805-07-06,실학자,4130000,14613000,0,4102000,1826000,24671000,False,False,True
3,홍경래,1780-01-01,1812-05-29,운동가,2880000,4134000,0,682000,1026000,8722000,False,False,True
4,신윤복,1758-01-01,1814-12-31,화가,1778000,8691000,0,2284000,202000,12955000,False,False,True

In [69]:
# 범주형 변수의 더미변수화 (원핫인코더)
from sklearn.preprocessing import OneHotEncoder

# One-Hot Encoder 적용
encoder = OneHotEncoder(sparse_output=False)
arr_encoded = encoder.fit_transform(df[['AGE']]) # df를 받아서 ndarray로 반환함

# 결과를 데이터 프레임으로 변환
df_encoded = pd.DataFrame(arr_encoded,
                          columns=encoder.get_feature_names_out(['AGE']))
# 새로운 변수 AGE_대한민국, AGE_일제강점기, AGE_조선후기가 생성됨
# 변수값은 1 (True), 0 (False)로 반환됨

# display(df_encoded.head())

# 원본 데이터 프레임과 결합
df = pd.concat([df, df_encoded], axis=1)     # 결합
df1 = df.drop('AGE', axis=1, inplace=False)  # 변환전 컬럼 'AGE' 삭제
                                             # inplace=False로 원본 유지
display(df1.head())

,NAME,BIRTH,DEATH,JOB,MBC,KBS,SBS,TVN,JTBC,TOTAL,AGE_대한민국,AGE_일제강점기,AGE_조선후기,AGE_대한민국,AGE_일제강점기,AGE_조선후기
0,홍대용,1731-03-01,1783-10-23,실학자,0,1630000,0,1170000,820000,3620000,0.0,0.0,1.0,0.0,0.0,1.0
1,정약종,1760-03-10,1801-02-26,종교인,0,599000,0,61000,0,660000,0.0,0.0,1.0,0.0,0.0,1.0
2,박제가,1750-11-05,1805-07-06,실학자,4130000,14613000,0,4102000,1826000,24671000,0.0,0.0,1.0,0.0,0.0,1.0
3,홍경래,1780-01-01,1812-05-29,운동가,2880000,4134000,0,682000,1026000,8722000,0.0,0.0,1.0,0.0,0.0,1.0
4,신윤복,1758-01-01,1814-12-31,화가,1778000,8691000,0,2284000,202000,12955000,0.0,0.0,1.0,0.0,0.0,1.0